### ISSUE TITLE
Question. Reuse older result.

### ISSUE THREAD

**Issue by dmitrylavrenov** [Fraunhofer-AISEC/cpg#102]
I would like to know is it possible the following.

1. There is a project, for example, with 1k files.
2. The project has been scanned and CPG has been created.
3. Several files have been changed.

Can I reuse the CPG from second point to run a new scan with changed files. The goal to improve performance in case the same big project but with a little difference like commit.

And what about performance improvements like multithreading. As I understand, there is a part that parses each file. Can it be done separately using multithreading ?

**Comment by Masrepus** [comment]
Regarding the incremental CPG creation, this is already something that we have planned, currently as a potential master's thesis topic, but it is not yet implemented.

The other point you mentioned about multithreading is not something we currently plan to do. I would also think that this will probably not increase the overall performance as much as incremental analysis would. The problem here ist that only the first part, creating the basic AST, is easily parallelizable. Anything afterwards, i.e. the passes for variable resolving, call resolving etc. need the whole graph to operate on, thus multithreading is rather difficult here.

Once incremental analysis is implemented, I would suspect that this can also serve as a way of running a single analysis in a parallel fashion, e.g. creating CPGs for each file individually and in separate threads, and joining them afterwards.

For now, if you have a big project and want to scan it, you can either create CPGs per file, which often suffices for a general overview, or scan it all at once, which unfortunately may take quite some time and memory.
