### ISSUE TITLE
Some nodes don't have a scope

### ISSUE THREAD

**Issue by seelchen** [Fraunhofer-AISEC/cpg#1021]
# Unexpected behavior

For Java code `BreakStatement`s, `CatchClause`s, `ContinueStatment`s and `TryStatement`s appear to have no scope set. 
When looking at the Java `StatementHandler` some of the `handle...` functions don't use the extension functions of the  MetadataProvider to get a new Node which might cause the missing scopes.

The scope for `CompoundStatement`s is also `null` but I am not sure if this is unexpected behavior.

# Changes to the configuration

```
TranslationConfiguration.builder()
            .defaultPasses()
            .defaultLanguages()
            .codeInNodes(true)
```

**Comment by oxisto** [comment]
> # Unexpected behavior
> For Java code `BreakStatement`s, `CatchClause`s, `ContinueStatment`s and `TryStatement`s appear to have no scope set. When looking at the Java `StatementHandler` some of the `handle...` functions don't use the extension functions of the MetadataProvider to get a new Node which might cause the missing scopes.
> 
> The scope for `CompoundStatement`s is also `null` but I am not sure if this is unexpected behavior.
> 
> # Changes to the configuration
> ```
> TranslationConfiguration.builder()
>             .defaultPasses()
>             .defaultLanguages()
>             .codeInNodes(true)
> ```

Interesting, you are right, some functions are directly using the `new` constructor, which they should not. Furthermore, instead of using the statement handler itself as metadata provider, it seems that some of the `newXXX` functions are using `frontend.getLanguage()` instead. While this works (the language class provides some metadata), it won't set the scope.
