### ISSUE TITLE
Missing data flow edges from out parameter of API call

### ISSUE THREAD

**Issue by for-just-we** [Fraunhofer-AISEC/cpg#1139]
The code I analyze contains some API call like `scanf`, this API usually reassign value to the variable. For example

```cpp
int main() {
    int a, b;
    scanf("%d, %d", &a, &b);
    int d = a + b;
    return 0;
}
```

The `scanf("%d, %d", &a, &b);` should define `a, b`, but I don't see the data-flow edge between `scanf("%d, %d", &a, &b);` and `a`. Does cpg support data-flow like this case? also the data-flow from other stdin like `cin >> a`.

The code I use is 

```java
File file = new File(sourceFile);
TranslationConfiguration configuration = new TranslationConfiguration.Builder().sourceLocations(file).defaultPasses().defaultLanguages().build();
TranslationManager translationManager = TranslationManager.builder().config(configuration).build();
TranslationResult translationResult = translationManager.analyze().get();
```

**Comment by KuechA** [comment]
Hi, sorry for the late reply. Since #1430 , it is possible to specify custom data flow behaviors for certain methods. The way to do this is specified/described [in our documentation page](https://fraunhofer-aisec.github.io/cpg/CPG/specs/dfg-function-summaries/). This should also help you with your problem since you should be able to model the DFG-edges for functions like `scanf`. However, for the stdin-case, this doesn't apply. Let us know if this helped you.
