### ISSUE TITLE
Question: As the formal code property graph combines the properties of ast, cfg and pdg. But i haven't seen pdg edges in the graph create by this framework, does it not take into account both the control dependencies and data dependencies while creating the final CPG?

### ISSUE THREAD

**Issue by Samarjeet93** [Fraunhofer-AISEC/cpg#140]

**Comment by Masrepus** [comment]
At the moment we don't have control dependency information in the CPG, that is correct. #95 will probably take some degree of control dependencies into account, but to what extent such information will be explicitly shown in the graph remains to be seen.

Concerning data dependencies, that is present in the CPG in form of the DFG edges. They're called "data flow graph" edges, but in the end they are more accurately described as data dependency graph edges. You can get more details about what the DFG models in this [explanation](https://github.com/Fraunhofer-AISEC/cpg/issues/98#issuecomment-629200064)

**Comment by Samarjeet93** [comment]
Thank you @Masrepus for the reply.  Read your thesis recently and was concerned about the drawbacks of not including the control dependencies in the CPG construction as control dependencies and data dependencies together play a vital role in identifying the properties of a vulnerability which was the main application of CPG .

**Comment by Masrepus** [comment]
That's true, without control dependencies we only get a superset of possible data dependencies, which may produce false positives when doing vulnerability scans. On the other hand I would argue false positives are more acceptable than false negatives in this area. Of course if we can reduce the potentially irrelevant parts of the data flow, this would be beneficial, which is why we started working on #95

**Comment by Samarjeet93** [comment]
Yeah, I saw that. Thanks,@Masrepus, really appreciate that you took out some time to reply to my queries.

**Comment by Masrepus** [comment]
No problem, any time!
