### ISSUE TITLE
Improve documentation of IncompleteType

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#158]
The semantics for `IncompleteType` is misleading, it seems to be the void type:

https://github.com/Fraunhofer-AISEC/cpg/blob/1024f02164d547f961c0f2f3a6d0642410ef6711/src/main/java/de/fraunhofer/aisec/cpg/graph/type/IncompleteType.java#L8

But why is it incomplete? Should it not rather be just `VoidType` or do I miss something here?

Intended for @vfsrfs.

**Comment by vfsrfs** [comment]
When implenting the TypeParser @titze and I decided to base the naming scheme of the TypeSystem on the C Standard (see [http://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf](http://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf) on page 33). The C Standard defines the semantics of incomplete type as objects with unknown size, therefore including not only void, but for example also arrays of unknown length. Right now we are using the IncompleteType only for void types and for the remaining use cases we are using the UnknownType. For this reason, it is perfectly conceivable to name VoidType, if this is what you prefer.

**Comment by oxisto** [comment]
Ah, understood. Well another possibility would be to use something like a PrimitiveType for all primitives, such as int and also void. Then void would not have a type just alone for itself. Or something like a BuiltinType.

While I agree that basing it on a standard makes perfect sense, I am not sure whether we want to constrain ourselves with the C99 standard, since a) we do support C++ up to C++17 and there are more built-in types, such as `nullptr` and b) we aim to support a myriad of "newer" languages, such as Java, and possibly Python in the future.

**Comment by vfsrfs** [comment]
I don’t that it is feasible to find a naming scheme that is general enough so that it adheres perfectly to every possible language scheme. At the time of defining the naming scheme for the typesystem we already took into consideration the C++17 Documentation and the Java Documentation. As all of the languages do define types very differently and even within the versions of a languages there are substantial contradictions, e.g. the use of the keyword auto in C++17 vs. C++11. For this reason, we had to make a compromise and we chose the C Standard because of the fact that its definition regarding the types was the most abstract and was most compatible between the three languages (C, C++, Java).

Regarding your suggestion of creating a primitiveType, we had also considered this categorization. Nonetheless, we decided against it, as for example combining int and void leads to more confusion, as you would have to leave out regular C++ Objects. Those objects can be thought of as a chunk of memory with a specific size, thus not being different than a int, whereas the void type does not have a fixed size and additionally it has a different behaviour. If you consider a function with the following signature `void foo(void)`, the use of `void` as parameter indicates that the function `foo` does not take any arguments, therefore the behaviour would be different if an int was used instead.

Another problem I see regarding BuiltinTypes is that by supporting other languages those Builtin-Types / Primitive-Types would be different for each language, as there are many cases where they are not compatible. For example, in Java there is the primitive data type byte, which is not present in C/C++. This would probably lead to having to differentiate between each language when performing analysis on the graph. The intended use case for the IncompleteType was to model type concepts that are only applicable to one specific language, such as void (not found in Java). With the IncompleteType it would also be possible to model concepts such as Null in C++/Java.

**Comment by oxisto** [comment]
I see that it seems that even C++17 defines void as an incomplete type, but the I would strongly suggest that we add some javadoc and general documentation to that class and to the `isIncompleteType` function, since it is not just `void` types but others as well. For example classes that are forward-declared, and so on (something that we are not dealing with at all at the moment).
