### ISSUE TITLE
ScopeManager vs. VariableUsageResolver

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#161]
There seems to be a lot of code within the ScopeManager to connect variables to fields, etc. - which seem unused. Additionally, there is the VariableUsageResolver. We should probably combine them into one class. Additionally, the VariableUsageResolver could make use of the new walker classes (#126).

The ScopeManager actually makes already a pretty good job of building the scope during the handle-functions (at least for CXX), so I am not quite sure why the VariableUsageResolver tries to re-emulate this later on in a pass. This causes some issues, i.e. seen in #152 and #155 because it does not correctly apply the scope of a class within C++ methods.

**Comment by Masrepus** [comment]
Correctly resolving field usages etc requires a full overview of the graph, e.g. when methods are defined before fields or when referring to fields from other classes. This is why the resolving process is done in a separate pass after the whole graph has been built. In my opinion, resolving variables during the AST building phase is not such a good idea, which is why I'm also not a big fan of merging the resolving procedures into the scope manager

**Comment by oxisto** [comment]
I agree, but then we should get rid of the leftover functions in the scope manager and we should still leverage the gathered scope information in the VariableUsageResolver. Otherwise we can get rid of the scope manager alltogether, since the gathered scopes are not retrieved at all later on it seems.

**Comment by Masrepus** [comment]
Using the scope manager in the variable resolver was something that was initially the goal, but the problem was that the scope manager state was lost between translation units. That's something @konradweiss wanted to fix, I'm unsure how far this has been accomplished.

All the variable resolving functions and the things concerning "bindings" were requested by Konrad to be left in place, he probably had some use for this in mind.

**Comment by konradweiss** [comment]
@oxisto @Masrepus Yes I was working on replacing the parts of the walker-functionality with the ScopeManager, which IMO is the way to go, with my changes ti the ScopeManager it is also possible to retrieve scopes by name and resolve fields of some used object (full overview of the graph you spoke about). The Scopes are build during last to cpg translation. Then later when using the ScopeManager in a Pass that resolves Variables the full overview is present.

**Comment by Masrepus** [comment]
Sounds good
