### ISSUE TITLE
Sanity check testPropagateArgumentsControlFlowInsensitive

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1806]
The behavior of the test `testPropagateArgumentsControlFlowInsensitive` is very questionable for both the `main` and the `small-dfg-fix` branches.
DFG edges should be investigated throughout this test case (declaration - function call - return).

**Comment by KuechA** [comment]
The test aims to check some functionality in the `DFGPass`, so the `ControlFlowSensitiveDFGPass` is disabled. Essentially, whenever we write to variable `a`, we expect a DFG edge to the `VariableDeclaration` (not the next usage) and for each read of `a`, we also have the `prevDFG` edge from the declaration. For this reason, we also expect the DFG declaration - call - declaration - return. (Note: the flow-sensitive case is tested in `testPropagateArguments()`.)

On the `small-dfg-fix` branch, the test currently fails because it relies on the DFGPass drawing the edges. However, on that branch, the respective method was commented out (`handleReference`). If we add this handling functionality and the usage of `ControlFlowSensitiveDFGPass::clearFlowsOfVariableDeclarations`, the test works as expected on this branch as well. In the current way, it doesn't make sense though, so I added `@Ignore`.
