### ISSUE TITLE
Parsing CXX template types with inner classes that have template types crash TypeParser

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#186]
The type parser logic still seems to have problems with some corner cases, such as templates classes that have an inner class that also has a template (in C++). For example `TypeParser.createFrom("OuterClass<int>::InnerClass<int>", true)` leads to:

```
java.lang.StringIndexOutOfBoundsException: begin 16, end 3, length 19
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.fixGenerics(TypeParser.java:274)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.createFrom(TypeParser.java:715)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.getGenerics(TypeParser.java:446)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.createFrom(TypeParser.java:784)
```

**Comment by oxisto** [comment]
Quick fix for now would be an extended try/catch around `TypeParser.createFrom` to return an UnknownType if it fails.

**Comment by vfsrfs** [comment]
The quickfix has already been implemented, however there is still an architectural issue on how to handle outer/inner classes in general and especially when both classes contain generics as in the example above.
Even if the exception  does not occur, it is still not clear how to deal with such a type, as right now this example would create one ObjectType with the name `Outer.Inner`. As a consequence, we only have one field for the generics. This implies that we cannot differentiate between the generics of the outer class and the generics of the inner class.

I would suggest to split the Outer.Inner class into two ObjectTypes and connect them with an edge, so that we can assign the generics to the corresponding class.
