### ISSUE TITLE
Field `annotations` must not be null, breaks OGM

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#192]
Commit 7d56eda487e8ec408b13036581d08b5e9800ff3e breaks the object graph mapper (OGM) of Codyze (and possibly Neo4J) and makes CPG structure ambiguous.

Collection fields of `Node`s must not be null.

Fields of classes in the CPG structure will result in either _edges_ or _properties_  of a node. The clearest way is to make that explicit by using the `@Relationship` annotation to enforce an edge. If that is not present, the OGM will investigate the value of the respective field and see if it is a `Node` type or Collection of `Node`s. This requires the field to be non-null, otherwise the OGM will consider it a property on the one hand, but not be able to provide type information on the other hand.

In its current form, Codyze will run into many `IllegalStateException`s.

**Comment by oxisto** [comment]
As mentioned in the PR, can you provide an example for a `IllegalStateException` that is actually not caught? This is caused by codize using `v.property()`without checking, if the property exists here:

https://github.com/Fraunhofer-AISEC/codyze/blob/600f7f1e4455b3f43a60af56467541e535aff387/src/main/java/de/fraunhofer/aisec/crymlin/connectors/db/OverflowDatabase.java#L347

But this exception is caught, so this not an issue. BTW this was already in 2.1.1, so not sure why you reverted the cpg-2.2.0 branch on codyze.

Also codyze does "correctly" consider the `annotations` field as a relationship (the call to `OverflowDatabase::mapsToRelationship` returns true). 

The issue is that codyze only sets the "xxxx_type" vertex property if, the object is non-null, but does not check, whether the "xxxx_type" property was set or not, but just access it using the `v.property()` line above.
