### ISSUE TITLE
Issues with (Literal<>) HashCode

### ISSUE THREAD

**Issue by lapplislazuli** [Fraunhofer-AISEC/cpg#248]
Hi there, 

I came across an issue using your library. 
I am parsing some java files and I was looking into the HashCodes of Nodes, where it seems that there are many collisions. 
The highest amount of collisions happens with Literal<String>, where actually every Literal<String> has the same hashcode. 

This seems to be due to using the hashcode method of node, which is quite generic and requires a name, but the Literal has no name (The value of the Literal is in the Code). 
There are apparently other issues with the same origin in the code, mostly for expressions. 

Potential fixes would be to include the code of the literal if existing, or use the name attribute of the Literal if given. 
Maybe the position should be added to the hashcode as well. 

Another similar issue is that the equals method seems to work as intended (that is, two literals with different Strings but same hashcode are unequal) , which leads to strange behavior when filtering for uniqueness. Some Libraries using equals-methods will give different distinct results than e.g. HashSet based ones. 

Related Files in SourceCode: 

- [Node Hashcode](https://github.com/Fraunhofer-AISEC/cpg/blob/f0dfe140418a2f5ac7f6bbb26afa28d967b8046e/src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java#L349)
- [Literal HashCode](https://github.com/Fraunhofer-AISEC/cpg/blob/f0dfe140418a2f5ac7f6bbb26afa28d967b8046e/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/Literal.java)

If you want I can prepare a Pull-Request fixing the hashcode-issues I encounter, but as the tests are rather sparse it might cause collisions in Projects using the (tainted) hashcode.

**Comment by Masrepus** [comment]
Producing hash codes for nodes turned out to be a rather delicate topic, as there are many cases where some nodes are added to hash sets belonging to other nodes at the very beginning of the graph building process. If at some later point, e.g. during passes, properties of these nodes are changed that are included in the hash code, the hash set where this node has previously been added to does not recognize it anymore due to the changed hash. This may then lead to the same node being added to a set multiple times etc.

This is why only properties that are known at the point in time where the node is first created are suitable for hash code inclusion. Thus, currently only the name and the node class are used for the hash code calculation. Having more collisions is not that much of an issue for us, which is why we didn't further optimize this behavior. For your case, I think that literals should set their name to their value, as this would clearly be the behavior I would intuitively expect from literals.

Other than that, the equals methods have been updated in PR #236, as some of them were rather outdated or could potentially lead to infinite loops depending on the graph structure.

**Comment by Twonki** [comment]
As a simple workaround in my Project I wrote a helper HashCode to Include all existing Values. 

```Java            
public int myHashCode(Node nn){
    if (nn == null)
         return 0;
    int result = 0;
    if(nn.getName() != null)
        result = nn.getName().hashCode();
    result = 31 * result + nn.getClass().getName().hashCode();

    if(nn.getCode() != null && !nn.getCode().isEmpty()){
         result = 31 * result + nn.getCode().hashCode();
    }
    if(nn.getLocation() != null){
            result = 31 * result + nn.getLocation().hashCode();
    }
    if(nn.getId() != null && nn.getId() != 0){
           result = 31 * result + nn.getId().intValue();
    }
    return result;
}
```

This still has some collisions, but down by factor 10. (Still open seem the 'DeclaredReferenceExpression'-Nodes but these are not that important for what I do). 

I think for a library the hashcode should at least try to fit standards or have a big fat warning upon it.

**Comment by oxisto** [comment]
> Producing hash codes for nodes turned out to be a rather delicate topic, as there are many cases where some nodes are added to hash sets belonging to other nodes at the very beginning of the graph building process. If at some later point, e.g. during passes, properties of these nodes are changed that are included in the hash code, the hash set where this node has previously been added to does not recognize it anymore due to the changed hash. This may then lead to the same node being added to a set multiple times etc.

Hmm do you have a good example of such a property change? At the moment I could only think of the EOG and DFG hash sets and I am not sure which property change of a pass will change them. Of course if you later on once the CPG is "finished" change property, you as a user need to take care of what this modification might entail. But the more I think about this topic, the less I see an actual problem in "properly" defining equals and hashCode using the elements of the individual nodes (minus some obvious problems with recursions)

**Comment by Masrepus** [comment]
For your purposes (processing the CPG after it is completely done) the hash method you provided makes absolute sense, however even just adding code to the hash code is not so trivial: In the CDT C/C++ parser, something like `void* method();` is split up so that what we parse as a method declaration is first thought to have the code `* method();`. Obviously, the `void` part is still missing, but this is only added **after** all processing of the method declaration node (creating a delcaration scope etc) is done. So, we added this node into a map in the scope manager while still containing the incomplete code string. Then, the code is changed, and the node inside the map is nowhere to be found

**Comment by Masrepus** [comment]
I added the fix that literals' names are set to their value to PR #236, which should resolve most of your hash collisions. And I added a more detailed warning to the hash code method. But the problem that hashmaps/sets may contain the same item multiple times, leading to lots of failed tests, can unfortunately easily be experienced by changing the hash code behavior.

**Comment by oxisto** [comment]
> For your purposes (processing the CPG after it is completely done) the hash method you provided makes absolute sense, however even just adding code to the hash code is not so trivial: In the CDT C/C++ parser, something like `void* method();` is split up so that what we parse as a method declaration is first thought to have the code `* method();`. Obviously, the `void` part is still missing, but this is only added **after** all processing of the method declaration node (creating a delcaration scope etc) is done. So, we added this node into a map in the scope manager while still containing the incomplete code string. Then, the code is changed, and the node inside the map is nowhere to be found

Ah, understood. This is actually something which could be fixed by a more concise way of setting the `code` property in this example (which is currently a total mess, sometimes it is set by the handler, sometimes by the `newX` function)

**Comment by Masrepus** [comment]
Yes, but when I looked at how stable hashing could be accomplished, the tradeoff between having more hash collisions (which by itself may make set lookups a bit slower, but won't lead to erroneous behavior if the equals function still works) and having to rewrite the whole handler structure while making sure that a set of properties remains unchanged just didn't seem right

**Comment by Twonki** [comment]
Thanks for the quick replies and the good explanations. 

For now my personal Workaround is resolving everything except for empty Return-Statements ('return;') which is good enough for what I do. 
From what my guts tell me to resolve most issues the Location or File (if given) of the Nodes is required to address it by a rule of thumb. But once the location enters the hashcode its a bit a philosophical question whether an empty return statement is the same node as another empty return statement somewhere else. This somehow depends on the context how it's supposed to be used which is application-specific?

Another thought I had would be to add a HashCode Pass? Does that Sound Reasonable ?

**Comment by Masrepus** [comment]
Hmm what I would imagine when thinking of a HashCode pass is that once the graph is all done, further calls to hashCode would be deviated to a secondary hashing function that takes more properties into account, by setting some kind of flag inside the nodes. Is that what you had in mind? One remaining problem I would see with that is that we would need to check whether there are any hash sets/maps that a CPG user might be interested in, that have been filled using the original hash code (name and class). Those would no longer work when switching the hash code strategy after completing the graph.

Location and file are also the things that I would guess to be relevant for proper identification, but the file is only set in a separate pass unfortunately. And I'm not sure about location, but I think that this is also updated at some later point in time, similar to the code property. I haven't checked that, but I would assume that the CDT will provide wrong location values for those nodes where it provides wrong code values
