### ISSUE TITLE
Analysis of Java files takes much longer with possible timeout

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/cpg#304]
We observe a heavy time penalty (and potential timeout) with CPG v3.3.0 vs. v3.2.0 when analyzing [AESCTR.java](https://github.com/Fraunhofer-AISEC/codyze/blob/59da2a92a5d6623d0066efb4bbae8d860a8485aa/src/test/resources/java/jca/AESCTR.java). In CPG v3.3.0 the analysis takes more than **10 minutes** compared to ~ 1 second in v3.2.0.

The problem occurs somewhere in the transformation part (i.e. between https://github.com/Fraunhofer-AISEC/cpg/blob/d70539dbbb9c8939f07b79785d45548bbb159761/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java#L133 and https://github.com/Fraunhofer-AISEC/cpg/blob/d70539dbbb9c8939f07b79785d45548bbb159761/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java#L169).

 I'm guessing that there is a long running loop or deep recursion somewhere in the `ScopeManger` or in the `DeclarationHandler`. Sorry that I cannot be more precise for now.

**Comment by oxisto** [comment]
Thanks for catching this on Codyze. Looks like we need to look into this and release a 3.2.1 hotfix

**Comment by oxisto** [comment]
At first glance, it *seems* that this was introduced in https://github.com/Fraunhofer-AISEC/cpg/pull/286.

@konradweiss Can I suggest that in the future we always use the **squash and merge**. While it nice for authors to have the original commits of regular merges, it makes finding the commit where things went sour like this very tiresome.

**Comment by oxisto** [comment]
The culprit seems to be the call here:
https://github.com/Fraunhofer-AISEC/cpg/blob/8ff52678dad57c9bc3e3a893640a0404fc4a171f/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java#L658

When parsing the line `System.out.printf("update  %2d: %32s [%s]\n", i, Utils.bytesToHex(ciphertextblock), Utils.bytesToHex(Mac))`.

This is a bit weird, since this function existed a long time. More specifically the call to `resolve` seems to cause the loop 
https://github.com/Fraunhofer-AISEC/cpg/blob/8ff52678dad57c9bc3e3a893640a0404fc4a171f/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java#L267

So maybe this a bug because of a newer version of JavaParser?

**Comment by oxisto** [comment]
Reverting back to JavaParser 3.17.0 fixes that.
