### ISSUE TITLE
`gradlew installDist` fails if Go is not installed

### ISSUE THREAD

**Issue by anushka192001** [Fraunhofer-AISEC/cpg#871]
thanks for providing this tutorial  to use cpg-console library 

https://www.youtube.com/watch?v=ngKtH6kYxx0 

this time i am using linux 
i cloned the whole cpg directory
but when i am trying to do ../gradlew installDist its showing this error . 
![image](https://user-images.githubusercontent.com/63954873/184537608-13b1c7cb-708b-470e-94d1-03f4b70b96fe.png)

![image](https://user-images.githubusercontent.com/63954873/184537640-6f9a2311-f43d-459c-b1c5-b73dd0fa9dd3.png)

![image](https://user-images.githubusercontent.com/63954873/184537645-848c9b51-f0f2-43ad-86d7-7d33a87a5877.png)

**Comment by oxisto** [comment]
Ah, you either need to have Go installed (in case you want to analyse programs in Go), otherwise you can exclude the Go frontend from being compiled if you run the following command from the cpg root: `./gradlew -x compileGolang installDist`. Then you should end up with a compiled console in `cpg-console/build/install/cpg-console/` which you can execute with `bin/cpg-console`. We need to adapt this step in the tutorial or make it clearer that Go is needed.

**Comment by anushka192001** [comment]
@oxisto  a new issue- i am not getting while using cpg-console library and using   :tr src/test/resources command on command line then in which format and where are the CPG's of  code files getting saved ?

![image](https://user-images.githubusercontent.com/63954873/185388199-be73451b-9130-4ac8-bdbf-4a58e98f7f26.png)

**Comment by KuechA** [comment]
Hi @anushka192001, good to know that you managed to import the project in the cpg-console.

If I understand your question correctly, you want to export the resulting graph and persist it somewhere on the disk, right? Unfortunately, the cpg-console doesn't offer such a functionality right now and is more suitable to view nodes and explore them manually.

If you want to export the graph, I'd suggest that you use the [cpg-neo4j subproject](https://github.com/Fraunhofer-AISEC/cpg/tree/main/cpg-neo4j). Once the graph is available in neo4j, you can use [APOC](https://neo4j.com/labs/apoc/4.1/export/) for example to export the graph in a number of representations. But, in my experience, it can take quite a while to import this graph again to neo4j and also, the textual representations are quite bloaty. Note that you have to run neo4j somewhere (e.g. as a docker container on your laptop but then you have to figure out how to configure the volumes of that container correctly for being able to access the files).

**Comment by anushka192001** [comment]
@KuechA  i want to save code property graphs of approximately 1 lakh files in my PC . would you please elaborate it more clearly.

**Comment by KuechA** [comment]
Since I'm not sure what exactly is your goal and in particular which format you need, it's hard to give you a precise recommendation. The CPG itself is usually kept in memory and is not persisted on the disk. If you need to save the graph, you have to rely on external tools to export the graphs.

The easiest option is probably to use the graph database neo4j for this task. You can run a local instance of neo4j as a docker container. Please check neo4j's documentation on how to run the container (e.g. see here: https://neo4j.com/labs/apoc/4.4/installation/#docker). Once this container is running, you can run `cpg-neo4j` (you find the documentation here: https://github.com/Fraunhofer-AISEC/cpg/tree/main/cpg-neo4j) to generate the graph. Now, you can use apoc to generate files which should then be saved in the docker container (and hopefully synchronized with your PC if you configured the docker volumes correctly). If you're not familiar with docker, or if you prefer to run neo4j locally, please refer to the neo4j documentation.
If necessary, you can even load these files back to neo4j later.

If none of the output formats fulfills your requirements, an alternative option could be to write a custom program to export the cpg (e.g., as shown in #776 ). Here, you benefit from full flexibility on the output.

**Comment by anushka192001** [comment]
@KuechA @oxisto if you have then would you also share the documentation of this project apart from given in this GitHub library .

**Comment by anushka192001** [comment]
@KuechA @oxisto  new issue- when using neo4j-cpg subproject , how to get the json or csv file individually of each code files at a time , not a single csv or json file of all the code files ?

**Comment by KuechA** [comment]
Hi, you could filter for a node's `file` property. Here's an example query which dumps all nodes belonging to a file to different json files:

```
match(n: Node)
with distinct n.file as distinctFiles
with collect(distinctFiles) as files
unwind range(0, size(files)-1) as i
call apoc.export.json.query("match (n1:Node) where n1.file = '" + files[i] + "' return *", "graph"+i+".json", {})
yield file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
return file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
```

**Comment by anushka192001** [comment]
> 

@KuechA  if i want to save  cpg json files with their names as that of code file what must be the change in this code?


match(n: Node)
with distinct n.file as distinctFiles
with collect(distinctFiles) as files
unwind range(0, size(files)-1) as i
call apoc.export.json.query("match (n1:Node) where n1.file = '" + files[i] + "' return *", "graph"+i+".json", {})
yield file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
return file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data

**Comment by KuechA** [comment]
Hi, to append the filename to the resulting json files, you would have to modify ` "graph"+i+".json"` to ` "graph"+files[i]+".json"`. However, I think this will lead to problems because the filename is the absolute path. Instead, I would suggest to output the filename which has been analyzed by changing the return value to ` return files[i], file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data`. This will allow you to easily map the analyzed file to the json file.

Second, you can modify the query of the apoc call to `"match (n1)-[r]->(n2) where n1.file = '" + files[i] + "' return *"`. If `n2` could also be from a different file than `n1`, you may have to extend the filter (the where clause).

So, the overall query would be
```
match(n: Node)
with distinct n.file as distinctFiles
with collect(distinctFiles) as files
unwind range(0, size(files)-1) as i
call apoc.export.json.query("match (n1)-[r]->(n2) where n1.file = '" + files[i] + "' return *", "graph"+i+".json", {})
yield file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
return files[i], file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
```
