### ISSUE TITLE
.json format of CPG's through this library is not understandable and not giving full information

### ISSUE THREAD

**Issue by anushka192001** [Fraunhofer-AISEC/cpg#935]
lets generating .JSON format of CPG of this sum.cpp file
![image](https://user-images.githubusercontent.com/63954873/194773884-32350a4f-f420-4d9c-8192-4b83bc95f0a8.png)

using cpg-neo4j subproject
![image](https://user-images.githubusercontent.com/63954873/194774460-f1bdad92-cce9-4bfe-94c2-481c4c493b1f.png)

downloading json from here
![image](https://user-images.githubusercontent.com/63954873/194774434-553b9d72-3d8d-402a-8a65-47f09b311d97.png)

![image](https://user-images.githubusercontent.com/63954873/194774595-5abd571f-7c87-4aa1-849b-31e22f98157c.png)

like as you can see this .json file , this is not giving even edges and relations information and completely not understandable . 

any other better way to get json file with complete information thought this library , i urgently need json files to train my machine learning model .

**Comment by KuechA** [comment]
Your query only matches on nodes but not on relationships between nodes (the edges). That's why the json only includes all the nodes but no edges. To fix this, you have to change the query. E.g., `MATCH (n) OPTIONAL MATCH (n)-[r]-(m) RETURN n,r,m` matches on all nodes and the edges. The json will now consist of a list of json objects with 3 elements (n, r, m), where the element "n" is the start node of an edge, "r" is the edge and "m" is the end node of the edge.

Concerning the interpretation of the output, the "identity" is an ID of the node, the "labels" determine the type of nodes, the "properties" are the properties of the node (please check the documentation of the graph). It just lists all the information which is available in the nodes.

**Comment by anushka192001** [comment]
@KuechA can you suggest me , which format is best for generating embeddings like graphson(json) or graphml(xml) ?

**Comment by KuechA** [comment]
We implemented a json export functionality in #1215 and thus close this issue for now.
