### ISSUE TITLE
DFG for MethodDeclaration node contains only ReturnStatement

### ISSUE THREAD

**Issue by dmitrylavrenov** [Fraunhofer-AISEC/cpg#98]
I have the following sample 

`
public class A{
    
    int x = 0;
    
    public void a(){
        b(x);
    }

    int y = 5;
    public void b(int z){
        System.out.println(z+y);
    }
}
`

I try to get node.prevDFG for node that presents b method with label MethodDeclaration. As we can see, the method depends on z and y. 

But node.prevDFG contains only the following

                  Class: class de.fraunhofer.aisec.cpg.graph.MethodDeclaration
		  Name: b
		  Code lines: [public void b(int z){,         System.out.println(z+y);,     }]
		  Start line: 10
		  DFG
			|
			|-
			  Class: class de.fraunhofer.aisec.cpg.graph.ReturnStatement
			  Name: 
			  Code lines: [return;]
			  DFG

**Comment by Masrepus** [comment]
I see what you mean, but that is not how the DFG is intended in our graph model. Here, a DFG edge means that the source node's value plays a role in the sink's value. So, for example if you consider an expression like `int y = getInt()`, we would see a DFG connection going from the method call `getInt()` towards `y`, as the call's return value will immediately affect the value of y. The call itself gets its data from the "value" of method `getInt()`. How do we define the value of a function? In our graph model this is its return value. This is the DFG edge you noticed between the method's return statement and the method itself. So transitively, the return value of the method affects the value of `y`. In order to better show this, I have created a small graphical example:

Of course would method parameters somehow influence what the method will return. But by default, there is no direct data flow here. Thus, DFG in your sample case will not be present between parameter `z` and method `b`.

**Comment by dmitrylavrenov** [comment]
Thank you, @Masrepus , for your good explanation. I've got it.

**Comment by Masrepus** [comment]
No problem. Feel free to ask further questions or report any bugs you may come across. We are always happy to help.

**Comment by dmitrylavrenov** [comment]
Sorry. Could somebody answer to 102 issue, it's a question ?
